name: Build and test RSVS3D

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: make
        run: make -f makelinux.mk all -j 2
        working-directory: SRCC/
      - uses: actions/upload-artifact@v2
        with:
          name: RSVS3D-ubuntu
          path: SRCC/RSVS3D
      - name: run tests
        run: ./RSVS3D --test
        working-directory: SRCC/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: install dependencies
        run: choco install make mingw
      - name: make
        run: make -f makewin.mk all -j 2
        working-directory: SRCC/
      - uses: actions/upload-artifact@v2
        with:
          name: RSVS3D-windows
          path: SRCC/RSVS3D*
      - name: run tests
        run: bin/RSVS3D.exe --test
        working-directory: SRCC/
