name: C/C++ CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: make
        run: make -f makelinux.mk all
        working-directory: SRCC/
      - name: run tests
        run: ./RSVS3D --test
        working-directory: SRCC/
