# Builds the documentation using Doxygen and deploys
# to gh-pages branch.
name: Documentation

on:
  push:
    branches: [develop, main, master]

jobs:
  build-documentation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Download doxygen 1.9.1
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-cpp9 libclang1-9
          curl https://www.doxygen.nl/files/doxygen-1.9.1.linux.bin.tar.gz | tar -xvz
      - name: Install doxygen
        run: |
          sudo make install
        working-directory: doxygen-1.9.1
      - name: Build documentation
        run: |
          doxygen docs/Doxyfile
          mkdir --parents docs/html/SRCC/docs
          cp docs/thesis*.pdf docs/html/SRCC/docs/
          cp docs/*.png docs/html/SRCC/docs/
        working-directory: SRCC
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: SRCC/docs/html/
