# Builds the documentation using Doxygen and deploys
# to gh-pages branch.
name: Documentation

on:
  push:
    branches: [develop, main, master]
  pull_request:
    branches: [develop]

jobs:
  build-documentation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: install doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
      - name: Build documentation
        run: |
          doxygen docs/Doxyfile
        working-directory: SRCC
      - name: Copy documentation
        run: |
          cp -r SRCC/docs/html/ ./public_html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public_html  # default: public
          branch: gh-pages
