# GitHub action for pre-commit hook
#
# While it would be desirable to use pre-commit.ci, I do not
# see a lot of support for installing other tools in the
# pre-commit CI image.
name: pre-commit

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install clang-format
      run: apt-get install clang-format
    - uses: pre-commit/action@v2.0.3
    - name: Install dependencies
